name: Deploy to GitHub Pages

# Run workflow on every push to the main branch
on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy-to-github-pages:
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish --configuration Release --no-build --output ./publish

    - name: Change base-href in index.html from / to EventEase
      run: sed -i 's/<base href="\/" \/>/<base href="\/EventEase\/" \/>/g' publish/wwwroot/index.html

    - name: Change base-href in 404.html from / to EventEase  
      run: sed -i 's/<base href="\/" \/>/<base href="\/EventEase\/" \/>/g' publish/wwwroot/404.html

    - name: Ensure 404.html exists and has the same structure as index.html
      run: |
        if [ ! -f publish/wwwroot/404.html ]; then
          cp publish/wwwroot/index.html publish/wwwroot/404.html
        fi

    - name: Add .nojekyll file
      run: touch publish/wwwroot/.nojekyll

    - name: Setup Pages
      uses: actions/configure-pages@v5
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './publish/wwwroot'
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4